Remove Apache commons-lang3 from dependencies
Apache commons-lang3 is now a dependency of Milton so we can get it as a transitive dependency.
Also having it in the POM with scope:test removes it from the build and generates NoClassDefFoundError: org/apache/commons/lang3/Range at runtime.