Upgrade dependencies
Starting with Spring Boot 3.5.4, using authn.class.name in templates throws exceptions
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "authn.class.name" (template: "layout.html" - line 28, col 14)
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1021E: A problem occurred whilst attempting to access the property 'name': 'Unable to access property 'name' through getter method'
Caused by: org.springframework.expression.AccessException: Unable to access property 'name' through getter method
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class

To avoid this issue, get the authentication class simple name from Java code and pass it as attribute to templates