Return 403 code if PROPFIND-based directory listing is denied (#107)
Motivation:

A client may attempt to list the contents of a private directory; i.e.,
a directory that the user (under which the StoRM WebDAV server is
running) does not have permission to enter (POSIX `x`) and list the
contents (POSIX `r`) then the server responds with a 500 Internal Server
error.

The log shows the following stack-trace is generated, indicating a bug:

```
java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
        at org.italiangrid.storm.webdav.milton.StoRMDirectoryResource.getChildren(StoRMDirectoryResource.java:89) ~[!/:1.7.1]
        at io.milton.http.webdav.DefaultPropFindPropertyBuilder.processResource(DefaultPropFindPropertyBuilder.java:181) ~[milton-server-ce-4.0.4.2305.jar!/:na]
        at io.milton.http.webdav.DefaultPropFindPropertyBuilder.appendResponses(DefaultPropFindPropertyBuilder.java:109) ~[milton-server-ce-4.0.4.2305.jar!/:na]
        at io.milton.http.webdav.DefaultPropFindPropertyBuilder.buildProperties(DefaultPropFindPropertyBuilder.java:87) ~[milton-server-ce-4.0.4.2305.jar!/:na]
[...]
```

Returning a 403 Forbidden status is arguably a better response (than
500) because the semantics of this status better describes the
underlying cause.

Modification:

Update `StoRMDirectoryResource` to handle `AccessDeniedException` by
throwing `NotAuthorizedException` when listing a directory.  The code is
updated to use the NIO2 `Files.list`, because the existing approach
does not provide information on why a directly listing failed.

If any other `IOException` is thrown during a directory listing then
this triggers `StoRMWebDAVError`, which triggered a similar 500 Internal
Server error.

Update `StoRMResourceFactory` to expose functionality of generating a
resource from a `File`.  This fixes code duplication between
`StoRMResourceFactory` and `StoRMDirectoryResource`.

Update `StoRMMiltonBehaviour` to handle any `NotAuthorizedException`
being thrown by returning a corresponding 403 Forbidden response.

Result:

StoRM WebDAV now provides a more helpful status code when attempting to
list the contents of a directory where the StoRM WebDAV user does not
have sufficient permission.

Closes: #107
Signed-off-by: Paul Millar <paul.millar@desy.de>